apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: testing123-deploy
    backstage.io/kubernetes-id: testing123-deploy
  name: testing123-deploy
  namespace: '{{ .Values.config.namespace }}'
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: testing123-deploy
