name: Deploy

on:
  repository_dispatch:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-20.04

    env:
      flex: "./flex.sh"
      AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
      AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
      ENV: '${{ github.event.client_payload.env }}'
      TAG: '${{ github.event.client_payload.tag }}'

    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Deploy
      run: $flex deploy
